### ISSUE TITLE
Hi, Does fbx animation supported?

### ISSUE THREAD

**Issue by jinfagang** [kimkulling/osre#133]
Hi, Does fbx animation supported?

**Comment by kimkulling** [comment]
Currently under development. I am working on a redesign for the Asset-Importer-Lib Animation support and I am planning to test them with the OSRE-Ed.

**Comment by jinfagang** [comment]
@kimkulling Hi, am really hoping for this feature! Do u have a timeline on when will OSRE support animation on FBX ? I'd like help to test on my platform.

**Comment by kimkulling** [comment]
At this moment, I do not have an accurate timeline. This is just a side project I am working on during my free time. So if you want to use this feature for production I strongly recommend using a different engine.

But if you want to help: welcome!

**Comment by jinfagang** [comment]
@kimkulling Hi, can u guide me a workable render engine (simple one, not game engine) that can succesfully render FBX animation based on ASSIMP?

I found there either very OLD projects using old tech like glut, or works only on windows. Does there any open source project   that meet my requirements? (I prefer using glad, glfw, assimp, glm, and that's all)
